# Generated by Django 5.1.6 on 2025-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='link',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='current_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='price_difference',
            field=models.IntegerField(default=0),
        ),
    ]
